version: '3.9'

services:
  sqlserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sqlserver
    environment:
      SA_PASSWORD: "#Gf24030085830"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"